version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
    